# Generated by Django 3.0.7 on 2020-06-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200607_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Tag', verbose_name='Parent Tag'),
        ),
    ]
