# Generated by Django 3.0.8 on 2021-03-09 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200719_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='post',
            name='image_sequence',
            field=models.ManyToManyField(blank=True, related_name='image_sequence', to='blog.Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_image', to='blog.Image'),
        ),
    ]
